gitGraph
    commit id: "Init repo mcn-sentinel-repo (baseline + all org dirs)"

    %% Dev + déploiement pour sentinel-mcn-dev
    commit id: "Change in baseline/ + sentinel-mcn-dev/"
    commit id: "CI: pipeline sentinel-mcn-dev -> deploy to Sentinel mcn-dev"

    %% Dev + déploiement pour sentinel-mcn-acceptation
    commit id: "Change in baseline/ + sentinel-mcn-acceptation/"
    commit id: "CI: pipeline sentinel-mcn-acceptation -> deploy to Sentinel mcn-acceptation"

    %% Dev + déploiement pour sentinel-mcn-prod
    commit id: "Change in baseline/ + sentinel-mcn-prod/"
    commit id: "CI: pipeline sentinel-mcn-prod -> deploy to Sentinel mcn-prod"

    %% Dev + déploiement pour sentinel-org1
    commit id: "Change in baseline/ + sentinel-org1/"
    commit id: "CI: pipeline sentinel-org1 -> deploy to Sentinel org1"

    %% Dev + déploiement pour sentinel-org2
    commit id: "Change in baseline/ + sentinel-org2/"
    commit id: "CI: pipeline sentinel-org2 -> deploy to Sentinel org2"

    %% Dev + déploiement pour sentinel-org3
    commit id: "Change in baseline/ + sentinel-org3/"
    commit id: "CI: pipeline sentinel-org3 -> deploy to Sentinel org3"
